name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        pip install buildozer cython
    
    - name: Create licenses
      run: |
        mkdir -p ~/.android
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/android-sdk-license
    
    - name: Build APK
      run: |
        # Используем системный NDK
        export ANDROIDNDK=/usr/local/lib/android/sdk/ndk/27.3.13750724
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: bin/*.apk
